# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Orchid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orchid

  target 'OrchidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OrchidUITests' do
    # Pods for testing
  end

end
